tests: stop using `freopen` in `test-fileio`
This helps get around a bug confusing `glibc` and making the test bail
out with the following error under `asan` on `x86`:

Fatal error: glibc detected an invalid stdio handle
Aborted (core dumped)

The bug has been reported in https://github.com/google/sanitizers/issues/778,
but it is unlikely to be fixed anytime soon.

(cherry picked from commit 362973902ca8501cad5e32db3820d7c66486b7a7)