sd-hwdb: include sys/stat.h in hwdb-internal.h
Include this header to fix errors when including hwdb-internal.h:
  ../src/libsystemd/sd-hwdb/hwdb-internal.h:16:21: error: field ‘st’ has incomplete type
     16 |         struct stat st;

(cherry picked from commit 9745b51c73c78a63003b4cb6e0714829144d297c)
(cherry picked from commit f00716615d54711f0fd584568f04615e4a206c05)