shared/microhttp-util: silence gcc warning
../src/journal-remote/microhttpd-util.c: In function ‘check_permissions’:
../src/journal-remote/microhttpd-util.c:301:5: error: function might be candidate for attribute ‘noreturn’ [-Werror=suggest-attribute=noreturn]
  301 | int check_permissions(struct MHD_Connection *connection, int *code, char **hostname) {
      |     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes #23630.

(cherry picked from commit b547241728487c0dca22780241b04964f2eb37af)
(cherry picked from commit ad74be8f3746dcca066860cbb23befada4af84c6)
(cherry picked from commit c62d033a9184d2225622114b481c9d5bd4b8b9b3)
(cherry picked from commit 8fb277817b748a521fee24782cf11cef092383f1)